services:
 app:
     build: .
     ports:
      - "8080:8080"
     depends_on:
      - pgvector
     environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://pgvector:5432/callibritydb
     - SPRING_DATASOURCE_USERNAME=user
     - SPRING_DATASOURCE_PASSWORD=password
     - SPRING_AI_OPENAI_API_KEY=${OPENAI_API_KEY}
     - SPRING_AI_VECTORSTORE_PGVECTOR_INITIALIZE_SCHEMA=true
     env_file:
     - .env
     links:
       - "pgvector:db"
     volumes:
       - ./src/main/resources/docs:/src/main/resources/docs

 pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=callibritydb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  docs_volume:
  pgdata:

